# Generated by Django 3.2 on 2023-05-30 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='profilemodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=500, null=True)),
                ('Email', models.CharField(blank=True, max_length=500, null=True)),
                ('profile_photo', models.ImageField(upload_to='')),
                ('companyName', models.CharField(blank=True, max_length=200, null=True)),
                ('projectDescription', models.CharField(blank=True, max_length=10000, null=True)),
                ('requiredSkill', models.CharField(blank=True, max_length=700, null=True)),
                ('projectDuration', models.CharField(blank=True, max_length=100, null=True)),
                ('bidingPrice', models.CharField(blank=True, max_length=500, null=True)),
                ('hireText', models.CharField(blank=True, max_length=500, null=True)),
                ('expectedPrice', models.CharField(blank=True, max_length=100, null=True)),
                ('deliveryDate', models.DateField(blank=True, null=True)),
                ('token', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
