# Generated by Django 3.2 on 2023-06-01 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_video', models.FileField(blank=True, null=True, upload_to='docs/')),
                ('upload_photo', models.ImageField(blank=True, null=True, upload_to='docs/photo/')),
                ('title', models.CharField(blank=True, max_length=10000000, null=True)),
                ('description', models.CharField(blank=True, max_length=10000000, null=True)),
                ('date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Twitter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chtml', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
