# Generated by Django 3.2 on 2023-10-05 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manual_news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsclass',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='docs/'),
        ),
    ]
